### ISSUE TITLE
IGalleryContext.AppGetFilesAsync explode com account can not be null

### ISSUE THREAD

**Issue by Rodrigo-Andrade** [vtex/gallery-context-net#8]
https://gist.github.com/Rodrigo-Andrade/7731fda4602e3b55d697

Exceção Sem Tratamento: System.AggregateException: Um ou mais erros. ---> System
.ArgumentNullException: Valor não pode ser nulo.
Nome do parâmetro: account
   em Vtex.Gallery.Context.Clients.ExtendedWorkspacesClient.<GetActiveSandboxesA
sync>d__5.MoveNext()
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---

   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   em Vtex.Gallery.Context.GalleryContextFactory.<CreateFromApiRequestAsync>d__6
.MoveNext()

**Comment by brunoabreu** [comment]
Resolvemos. https://github.com/vtex/gallery-context-net/commit/1a43c97009a0285c7f234292f08330e3ff742a7d

Foi lançada uma versão nova do Gallery Context [(v0.3.3)](https://www.nuget.org/packages/Vtex.Gallery.Context/0.3.3) com a correção.
